import {
  // general / brand
  FaHeartbeat,
  FaUserMd,
  FaUserNurse,
  FaShieldAlt,
  FaHospital,
  FaClinicMedical,
  FaRegCalendarCheck,
  FaListUl,
  FaMagic,
  FaCheckCircle,
  FaStar,
  FaArrowRight,
  FaPhoneAlt,
  FaWhatsapp,
  FaMapMarkerAlt,
  FaEnvelope,
  FaClock,
  FaInstagram,
  FaFacebookF,
  FaYoutube,
  FaLinkedinIn,
  // specialties
  FaStethoscope,
  FaBone,
  FaBaby,
  FaVenus,
  FaProcedures,
  FaAssistiveListeningSystems,
  FaEye,
  FaBrain,
  FaAllergies,
  FaNotesMedical,
  FaTint,
  FaLungs,
  FaTooth,
  FaTeeth,
  // facilities / services
  FaAmbulance,
  FaFlask,
  FaMicroscope,
  FaXRay,
  FaPills,
  FaSyringe,
  FaWheelchair,
  FaBed,
  FaDna,
  FaFileMedical,
  FaHandHoldingHeart,
  // people / careers
  FaUsers,
  FaAward,
  FaBriefcase,
  FaGraduationCap,
  FaRupeeSign,
  FaChild,
  FaSmile,
  FaAlignCenter,
  // kids zone
  FaAppleAlt,
  FaCarrot,
  FaFish,
  FaLeaf,
  FaEgg,
  FaCookie,
  FaIceCream,
  FaCandyCane,
  FaBirthdayCake,
  FaPumpSoap,
  FaHandsWash,
  FaMoon,
  FaRunning,
  FaThermometerHalf,
  FaBandAid,
  FaHeadSideMask,
  FaMedal,
  FaPrescriptionBottleAlt,
  FaSmileBeam,
  FaHandshake,
  FaClipboardList,
  FaHeart,
} from "react-icons/fa";

const map = {
  // brand / general
  heart: FaHeartbeat,
  heartbeat: FaHeartbeat,
  userMd: FaUserMd,
  nurse: FaUserNurse,
  shield: FaShieldAlt,
  hospital: FaHospital,
  clinic: FaClinicMedical,
  calendar: FaRegCalendarCheck,
  list: FaListUl,
  sparkle: FaMagic,
  check: FaCheckCircle,
  star: FaStar,
  arrow: FaArrowRight,
  phone: FaPhoneAlt,
  whatsapp: FaWhatsapp,
  pin: FaMapMarkerAlt,
  email: FaEnvelope,
  clock: FaClock,
  instagram: FaInstagram,
  facebook: FaFacebookF,
  youtube: FaYoutube,
  linkedin: FaLinkedinIn,

  // specialties / departments
  stethoscope: FaStethoscope,
  bone: FaBone,
  baby: FaBaby,
  gynae: FaVenus,
  surgery: FaProcedures,
  ent: FaAssistiveListeningSystems,
  eye: FaEye,
  brain: FaBrain,
  derma: FaAllergies,
  gastro: FaNotesMedical,
  kidney: FaTint,
  tint: FaTint,
  lungs: FaLungs,
  tooth: FaTooth,
  teeth: FaTeeth,
  implant: FaTooth,
  smile: FaSmile,
  align: FaAlignCenter,
  kids: FaChild,

  // facilities / services
  ambulance: FaAmbulance,
  lab: FaFlask,
  flask: FaFlask,
  microscope: FaMicroscope,
  xray: FaXRay,
  pills: FaPills,
  syringe: FaSyringe,
  physio: FaWheelchair,
  wheelchair: FaWheelchair,
  bed: FaBed,
  dna: FaDna,
  fileMedical: FaFileMedical,
  handHeart: FaHandHoldingHeart,
  notes: FaNotesMedical,

  // people / careers
  users: FaUsers,
  award: FaAward,
  briefcase: FaBriefcase,
  graduation: FaGraduationCap,
  rupee: FaRupeeSign,

  // kids zone
  apple: FaAppleAlt,
  carrot: FaCarrot,
  fish: FaFish,
  leaf: FaLeaf,
  egg: FaEgg,
  cookie: FaCookie,
  icecream: FaIceCream,
  candy: FaCandyCane,
  cake: FaBirthdayCake,
  soap: FaPumpSoap,
  wash: FaHandsWash,
  moon: FaMoon,
  run: FaRunning,
  thermometer: FaThermometerHalf,
  bandage: FaBandAid,
  mask: FaHeadSideMask,
  medal: FaMedal,
  prescription: FaPrescriptionBottleAlt,
  smileBeam: FaSmileBeam,
  handshake: FaHandshake,
  clipboard: FaClipboardList,
  loveHeart: FaHeart,
};

/** Renders a named icon. Falls back to a medical-notes glyph if key is unknown. */
export default function Icon({ name, className = "", ...rest }) {
  const Cmp = map[name] || FaNotesMedical;
  return <Cmp className={className} aria-hidden="true" {...rest} />;
}
